### ISSUE TITLE
Recomendación para el formato de nombre de archivos y comandos

### ISSUE THREAD

**Issue by rodrigo-morales-1** [SweetRiot/sweetRiot.github.io#1]
Acabo de leer tu artículo sobre el uso de NGINX. Personalmente, no tengo mucha experiencia con NGINX y me pareció muy interesante lo que mencionaste en esta parte. 

> Lo más alucinante de todo esto es que tuve 3 servidores web corriendo, 2 en Linux y 1 en Windows, en diferentes máquinas y NGINX me lo enviaba correctamente.

No sabía que era posible configurar NGINX para redireccionar solicitud a aplicaciones corriendo en diferentes sistemas operativos. Gracias por compartir conocimiento.

Aprovecho para darte una recomendación para tus siguientes artículos: Puedes encerrar los nombres de directorios con [acentos graves](https://es.wikipedia.org/wiki/Acento_grave) para que sean formateados con [tipo de letra monoespaciado](https://es.wikipedia.org/wiki/Tipo_de_letra_monoespaciado), así los lectores podrían saber convenientemente que una palabra es un nombre de un archivo o un comando. En tu artículo, podrías encerrar `sites-available`, `sites-enable` y `sudo systemctl reload nginx` para que se vean como lo acabas de ver. Por ejemplo, esta parte:

https://github.com/SweetRiot/sweetRiot.github.io/blob/3d8dfdc967ebdf546f32d6dc82d9fefc8f7e674b/_posts/2023-10-14-Aprendiendo%20a%20usar%20NGINX.markdown?plain=1#L24

podría ser escrita como:

```
 Luego recagar las configuraciones al servicio de NGINX que ya estaba corriendo, usé `sudo systemctl reload nginx`
```

para que se vea así:

>  Luego recagar las configuraciones al servicio de NGINX que ya estaba corriendo, usé `sudo systemctl reload nginx`

**Comment by SweetRiot** [comment]
Buenísimo, Rodrigo, gracias por la recomendación :D lo usaré

**Comment by rodrigo-morales-1** [comment]
No hay problema. Es bueno aprender constantemente. Gracias por compartir conocimmiento.
